apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: rt-get-brokerage-type
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-brokerage-type
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/brokerage_type
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/brokerage_type
